2024-10-21 18:04:34,945 INFO: Loaded main_inventory.xlsx from S3. [in /Users/william/validate/inventory_validation/app.py:92]
2024-10-21 18:04:34,952 INFO: 'processing_timestamp' column converted to datetime. [in /Users/william/validate/inventory_validation/app.py:132]
2024-10-21 18:04:34,955 INFO: Reset processing flags for SKU 'DA-0280' due to timeout. [in /Users/william/validate/inventory_validation/app.py:160]
2024-10-21 18:04:37,065 INFO: Saved main_inventory.xlsx to S3. [in /Users/william/validate/inventory_validation/app.py:143]
2024-10-21 18:04:37,065 INFO: Stale processing flags have been reset. [in /Users/william/validate/inventory_validation/app.py:164]
2024-10-21 18:04:38,769 INFO: Saved main_inventory.xlsx to S3. [in /Users/william/validate/inventory_validation/app.py:143]
2024-10-21 18:58:46,362 INFO: Inventory Validation Startup [in /Users/william/validate/inventory_validation/app/__init__.py:35]
2024-10-21 18:58:47,719 INFO: Inventory Validation Startup [in /Users/william/validate/inventory_validation/app/__init__.py:35]
2024-10-21 19:00:43,586 INFO: Inventory Validation Startup [in /Users/william/validate/inventory_validation/app/__init__.py:30]
2024-10-21 19:00:48,525 ERROR: An error occurred in main route: [Errno 45] Operation not supported: '/home/ec2-user' [in /Users/william/validate/inventory_validation/app/routes/main.py:190]
2024-10-21 19:00:48,689 ERROR: An error occurred in main route: [Errno 45] Operation not supported: '/home/ec2-user' [in /Users/william/validate/inventory_validation/app/routes/main.py:190]
2024-10-21 19:00:48,839 ERROR: An error occurred in main route: [Errno 45] Operation not supported: '/home/ec2-user' [in /Users/william/validate/inventory_validation/app/routes/main.py:190]
2024-10-21 19:00:48,988 ERROR: An error occurred in main route: [Errno 45] Operation not supported: '/home/ec2-user' [in /Users/william/validate/inventory_validation/app/routes/main.py:190]
2024-10-21 19:00:49,148 ERROR: An error occurred in main route: [Errno 45] Operation not supported: '/home/ec2-user' [in /Users/william/validate/inventory_validation/app/routes/main.py:190]
2024-10-21 19:00:49,310 ERROR: An error occurred in main route: [Errno 45] Operation not supported: '/home/ec2-user' [in /Users/william/validate/inventory_validation/app/routes/main.py:190]
2024-10-21 19:00:49,459 ERROR: An error occurred in main route: [Errno 45] Operation not supported: '/home/ec2-user' [in /Users/william/validate/inventory_validation/app/routes/main.py:190]
2024-10-21 19:00:49,612 ERROR: An error occurred in main route: [Errno 45] Operation not supported: '/home/ec2-user' [in /Users/william/validate/inventory_validation/app/routes/main.py:190]
2024-10-21 19:00:49,760 ERROR: An error occurred in main route: [Errno 45] Operation not supported: '/home/ec2-user' [in /Users/william/validate/inventory_validation/app/routes/main.py:190]
2024-10-21 19:00:49,908 ERROR: An error occurred in main route: [Errno 45] Operation not supported: '/home/ec2-user' [in /Users/william/validate/inventory_validation/app/routes/main.py:190]
2024-10-21 19:00:50,083 ERROR: An error occurred in main route: [Errno 45] Operation not supported: '/home/ec2-user' [in /Users/william/validate/inventory_validation/app/routes/main.py:190]
2024-10-21 19:00:50,231 ERROR: An error occurred in main route: [Errno 45] Operation not supported: '/home/ec2-user' [in /Users/william/validate/inventory_validation/app/routes/main.py:190]
2024-10-21 19:00:50,378 ERROR: An error occurred in main route: [Errno 45] Operation not supported: '/home/ec2-user' [in /Users/william/validate/inventory_validation/app/routes/main.py:190]
2024-10-21 19:00:50,528 ERROR: An error occurred in main route: [Errno 45] Operation not supported: '/home/ec2-user' [in /Users/william/validate/inventory_validation/app/routes/main.py:190]
2024-10-21 19:00:50,678 ERROR: An error occurred in main route: [Errno 45] Operation not supported: '/home/ec2-user' [in /Users/william/validate/inventory_validation/app/routes/main.py:190]
2024-10-21 19:00:50,829 ERROR: An error occurred in main route: [Errno 45] Operation not supported: '/home/ec2-user' [in /Users/william/validate/inventory_validation/app/routes/main.py:190]
2024-10-21 19:00:50,978 ERROR: An error occurred in main route: [Errno 45] Operation not supported: '/home/ec2-user' [in /Users/william/validate/inventory_validation/app/routes/main.py:190]
2024-10-21 19:00:51,125 ERROR: An error occurred in main route: [Errno 45] Operation not supported: '/home/ec2-user' [in /Users/william/validate/inventory_validation/app/routes/main.py:190]
2024-10-21 19:00:51,287 ERROR: An error occurred in main route: [Errno 45] Operation not supported: '/home/ec2-user' [in /Users/william/validate/inventory_validation/app/routes/main.py:190]
2024-10-21 19:00:51,440 ERROR: An error occurred in main route: [Errno 45] Operation not supported: '/home/ec2-user' [in /Users/william/validate/inventory_validation/app/routes/main.py:190]
2024-10-21 19:00:52,658 ERROR: An error occurred in main route: [Errno 45] Operation not supported: '/home/ec2-user' [in /Users/william/validate/inventory_validation/app/routes/main.py:190]
2024-10-21 19:00:52,831 ERROR: An error occurred in main route: [Errno 45] Operation not supported: '/home/ec2-user' [in /Users/william/validate/inventory_validation/app/routes/main.py:190]
2024-10-21 19:00:53,008 ERROR: An error occurred in main route: [Errno 45] Operation not supported: '/home/ec2-user' [in /Users/william/validate/inventory_validation/app/routes/main.py:190]
2024-10-21 19:00:53,188 ERROR: An error occurred in main route: [Errno 45] Operation not supported: '/home/ec2-user' [in /Users/william/validate/inventory_validation/app/routes/main.py:190]
2024-10-21 19:00:53,370 ERROR: An error occurred in main route: [Errno 45] Operation not supported: '/home/ec2-user' [in /Users/william/validate/inventory_validation/app/routes/main.py:190]
2024-10-21 19:00:53,530 ERROR: An error occurred in main route: [Errno 45] Operation not supported: '/home/ec2-user' [in /Users/william/validate/inventory_validation/app/routes/main.py:190]
2024-10-21 19:00:53,679 ERROR: An error occurred in main route: [Errno 45] Operation not supported: '/home/ec2-user' [in /Users/william/validate/inventory_validation/app/routes/main.py:190]
2024-10-21 19:00:53,847 ERROR: An error occurred in main route: [Errno 45] Operation not supported: '/home/ec2-user' [in /Users/william/validate/inventory_validation/app/routes/main.py:190]
2024-10-21 19:00:54,003 ERROR: An error occurred in main route: [Errno 45] Operation not supported: '/home/ec2-user' [in /Users/william/validate/inventory_validation/app/routes/main.py:190]
2024-10-21 19:00:54,154 ERROR: An error occurred in main route: [Errno 45] Operation not supported: '/home/ec2-user' [in /Users/william/validate/inventory_validation/app/routes/main.py:190]
2024-10-21 19:00:54,309 ERROR: An error occurred in main route: [Errno 45] Operation not supported: '/home/ec2-user' [in /Users/william/validate/inventory_validation/app/routes/main.py:190]
2024-10-21 19:00:54,461 ERROR: An error occurred in main route: [Errno 45] Operation not supported: '/home/ec2-user' [in /Users/william/validate/inventory_validation/app/routes/main.py:190]
2024-10-21 19:00:54,618 ERROR: An error occurred in main route: [Errno 45] Operation not supported: '/home/ec2-user' [in /Users/william/validate/inventory_validation/app/routes/main.py:190]
2024-10-21 19:00:54,778 ERROR: An error occurred in main route: [Errno 45] Operation not supported: '/home/ec2-user' [in /Users/william/validate/inventory_validation/app/routes/main.py:190]
2024-10-21 19:00:54,930 ERROR: An error occurred in main route: [Errno 45] Operation not supported: '/home/ec2-user' [in /Users/william/validate/inventory_validation/app/routes/main.py:190]
2024-10-21 19:00:55,107 ERROR: An error occurred in main route: [Errno 45] Operation not supported: '/home/ec2-user' [in /Users/william/validate/inventory_validation/app/routes/main.py:190]
2024-10-21 19:00:55,380 ERROR: An error occurred in main route: [Errno 45] Operation not supported: '/home/ec2-user' [in /Users/william/validate/inventory_validation/app/routes/main.py:190]
2024-10-21 19:00:55,554 ERROR: An error occurred in main route: [Errno 45] Operation not supported: '/home/ec2-user' [in /Users/william/validate/inventory_validation/app/routes/main.py:190]
2024-10-21 19:00:55,721 ERROR: An error occurred in main route: [Errno 45] Operation not supported: '/home/ec2-user' [in /Users/william/validate/inventory_validation/app/routes/main.py:190]
2024-10-21 19:00:55,883 ERROR: An error occurred in main route: [Errno 45] Operation not supported: '/home/ec2-user' [in /Users/william/validate/inventory_validation/app/routes/main.py:190]
2024-10-21 19:19:20,958 INFO: Inventory Validation Startup [in /Users/william/validate/inventory_validation/app/__init__.py:30]
2024-10-21 19:19:22,227 INFO: Inventory Validation Startup [in /Users/william/validate/inventory_validation/app/__init__.py:30]
2024-10-21 19:19:33,770 INFO: Loaded main_inventory_staging.xlsx from S3. [in /Users/william/validate/inventory_validation/app/utils/inventory.py:32]
2024-10-21 19:19:33,771 INFO: 'processing' column added with default False values. [in /Users/william/validate/inventory_validation/app/utils/inventory.py:72]
2024-10-21 19:19:33,772 INFO: 'assigned_to' column added with default None values. [in /Users/william/validate/inventory_validation/app/utils/inventory.py:75]
2024-10-21 19:19:33,772 INFO: 'processing_timestamp' column added with default NaT values. [in /Users/william/validate/inventory_validation/app/utils/inventory.py:78]
2024-10-21 19:19:36,291 INFO: Saved main_inventory_staging.xlsx to S3. [in /Users/william/validate/inventory_validation/app/utils/inventory.py:100]
2024-10-21 19:19:49,235 INFO: Loaded main_inventory_staging.xlsx from S3. [in /Users/william/validate/inventory_validation/app/utils/inventory.py:32]
2024-10-21 19:19:49,237 INFO: 'processing_timestamp' column converted to datetime. [in /Users/william/validate/inventory_validation/app/utils/inventory.py:82]
